version: '3.8'

services:
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - /mnt/c/configs/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
    env_file:
      - /mnt/c/configs/.env
    depends_on:
      - database

  database:
    image: postgres:14  # Using official postgres image instead of custom build
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - /mnt/c/configs/.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: