version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: wellversed
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: wellversed_db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://wellversed:devpassword@db:5432/wellversed_db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: