version: '3.8'

services:
  # Local Cognito simulator for development
  cognito-local:
    image: jagregory/cognito-local:latest
    ports:
      - "9229:9229"
    volumes:
      - ./cognito-local-config:/app/.cognito
    environment:
      - DEBUG=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9229/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USER:-wellversed_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME:-wellversed_db}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wellversed_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      cognito-local:
        condition: service_healthy
    environment:
      # Database
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-wellversed_db}
      DATABASE_USER: ${DATABASE_USER:-wellversed_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      
      # Frontend
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:4200}
      
      # API Bible (use test key for local)
      API_BIBLE_KEY: ${API_BIBLE_KEY}
      API_BIBLE_HOST: ${API_BIBLE_HOST:-https://api.scripture.api.bible}
      DEFAULT_BIBLE_ID: ${DEFAULT_BIBLE_ID:-de4e12af7f28f599-02}
      
      # Cognito Local
      ENVIRONMENT: ${ENVIRONMENT:-local}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID:-local_pool_id}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID:-local_client_id}
      COGNITO_CLIENT_SECRET: ${COGNITO_CLIENT_SECRET}
      COGNITO_DOMAIN: ${COGNITO_DOMAIN:-http://cognito-local:9229}
      COGNITO_JWKS_URI: ${COGNITO_JWKS_URI:-http://cognito-local:9229/.well-known/jwks.json}
      COGNITO_ISSUER: ${COGNITO_ISSUER:-http://cognito-local:9229}
      
      # JWT & Test Credentials
      LOCAL_JWT_SECRET: ${LOCAL_JWT_SECRET}
      LOCAL_TEST_USERS: ${LOCAL_TEST_USERS:-test@example.com}
      LOCAL_TEST_PASSWORD: ${LOCAL_TEST_PASSWORD}
      
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  postgres_data: