name: AI PR

on:
  workflow_dispatch:
    inputs:
      task:
        description: "What should the agent do?"
        required: true
      model:
        description: "OpenAI model (e.g., gpt-4.1-mini, o3-mini)"
        required: false
        default: "gpt-4.1-mini"
      reasoning_effort:
        description: "o-series effort (low/medium/high). Ignored for GPT models."
        required: false
        default: "low"

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install --upgrade openai

      - name: Generate and apply patch
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TASK: ${{ inputs.task }}
          MODEL: ${{ inputs.model }}
          REASONING_EFFORT: ${{ inputs.reasoning_effort }}
          # Only let the agent edit these directories by default
          ALLOWED_DIRS: backend/,frontend/,sql_setup/
          # Safety cap on total +/- lines in the diff
          MAX_EDIT_LINES: "1200"
        run: |
          python .github/agent_patch.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: ai/agent
          branch-suffix: timestamp
          commit-message: |
            chore(agent): ${{ inputs.task }}
          title: "AI: ${{ inputs.task }}"
          body: |
            Task:
            > ${{ inputs.task }}

            Model: `${{ inputs.model }}`
            Effort: `${{ inputs.reasoning_effort }}`

          draft: false
